<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Certiflow.Compliance.Api</RootNamespace>
    <UserSecretsId>certiflow-compliance-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../shared/Certiflow.Http/Certiflow.Http.csproj" />
    <ProjectReference Include="../Certiflow.Compliance.Application/Certiflow.Compliance.Application.csproj" />
    <ProjectReference Include="../Certiflow.Compliance.Infrastructure/Certiflow.Compliance.Infrastructure.csproj" />
  </ItemGroup>

</Project>
