// <auto-generated />
using System;
using Certiflow.Intake.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Certiflow.Intake.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IntakeDbContext))]
    partial class IntakeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("intake")
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Certiflow.Intake.Domain.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("document_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("ExpectedDocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("expected_document_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("file_name");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int")
                        .HasColumnName("page_count");

                    b.Property<string>("QuarantineReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("quarantine_reason");

                    b.Property<Guid?>("RequirementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("requirement_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersededByDocumentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("superseded_by_document_id");

                    b.Property<Guid?>("SupersedesDocumentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supersedes_document_id");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId", "RequirementId")
                        .HasDatabaseName("ix_documents_supplier_requirement");

                    b.ToTable("documents", "intake");
                });

            modelBuilder.Entity("Certiflow.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("received_at");

                    b.HasKey("MessageId");

                    b.ToTable("inbox", "intake");
                });

            modelBuilder.Entity("Certiflow.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<int>("PublishAttempts")
                        .HasColumnType("int")
                        .HasColumnName("publish_attempts");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("published_at");

                    b.HasKey("EventId");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_pending")
                        .HasFilter("[published_at] IS NULL");

                    b.ToTable("outbox", "intake");
                });

            modelBuilder.Entity("Certiflow.Intake.Domain.Document", b =>
                {
                    b.OwnsOne("Certiflow.Intake.Domain.Sha256Hash", "Sha256", b1 =>
                        {
                            b1.Property<Guid>("DocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("sha256");

                            b1.HasKey("DocumentId");

                            b1.ToTable("documents", "intake");

                            b1.WithOwner()
                                .HasForeignKey("DocumentId");
                        });

                    b.OwnsOne("Certiflow.Intake.Domain.StorageReference", "StorageReference", b1 =>
                        {
                            b1.Property<Guid>("DocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BlobPath")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("nvarchar(1024)")
                                .HasColumnName("storage_blob_path");

                            b1.Property<string>("Container")
                                .IsRequired()
                                .HasMaxLength(63)
                                .HasColumnType("nvarchar(63)")
                                .HasColumnName("storage_container");

                            b1.HasKey("DocumentId");

                            b1.ToTable("documents", "intake");

                            b1.WithOwner()
                                .HasForeignKey("DocumentId");
                        });

                    b.Navigation("Sha256")
                        .IsRequired();

                    b.Navigation("StorageReference")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
