// <auto-generated />
using System;
using Certiflow.Intelligence.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Certiflow.Intelligence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IntelligenceDbContext))]
    [Migration("20260821200424_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("intelligence")
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Certiflow.Intelligence.Infrastructure.Persistence.ExtractionJobRecord", b =>
                {
                    b.Property<Guid>("ExtractionJobId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("extraction_job_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("attempt_count");

                    b.Property<decimal>("AutoAcceptThreshold")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("auto_accept_threshold");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("document_id");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("document_type");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("FieldsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fields_json");

                    b.Property<bool>("IsAutoAcceptable")
                        .HasColumnType("bit")
                        .HasColumnName("is_auto_acceptable");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("model_used");

                    b.Property<decimal>("OverallConfidence")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("overall_confidence");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("prompt_version");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("requirement_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<string>("TextSource")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("text_source");

                    b.Property<int>("TokensConsumed")
                        .HasColumnType("int")
                        .HasColumnName("tokens_consumed");

                    b.HasKey("ExtractionJobId");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_extraction_jobs_document");

                    b.ToTable("extraction_jobs", "intelligence");
                });

            modelBuilder.Entity("Certiflow.Intelligence.Infrastructure.Persistence.RequirementRecord", b =>
                {
                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("requirement_id");

                    b.Property<string>("AcceptedIssuersPacked")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("accepted_issuers");

                    b.Property<decimal>("AutoAcceptThreshold")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("auto_accept_threshold");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("document_type");

                    b.Property<bool>("RequiresIssuerMatch")
                        .HasColumnType("bit")
                        .HasColumnName("requires_issuer_match");

                    b.HasKey("RequirementId");

                    b.ToTable("requirements", "intelligence");
                });

            modelBuilder.Entity("Certiflow.Intelligence.Infrastructure.Persistence.SupplierRecord", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("TradingName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("trading_name");

                    b.HasKey("SupplierId");

                    b.ToTable("suppliers", "intelligence");
                });

            modelBuilder.Entity("Certiflow.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("received_at");

                    b.HasKey("MessageId");

                    b.ToTable("inbox", "intelligence");
                });

            modelBuilder.Entity("Certiflow.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<int>("PublishAttempts")
                        .HasColumnType("int")
                        .HasColumnName("publish_attempts");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("published_at");

                    b.HasKey("EventId");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_pending")
                        .HasFilter("[published_at] IS NULL");

                    b.ToTable("outbox", "intelligence");
                });
#pragma warning restore 612, 618
        }
    }
}
