// <auto-generated />
using System;
using Certiflow.SupplierRegistry.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Certiflow.SupplierRegistry.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RegistryDbContext))]
    [Migration("20260821200351_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("registry")
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Certiflow.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("received_at");

                    b.HasKey("MessageId");

                    b.ToTable("inbox", "registry");
                });

            modelBuilder.Entity("Certiflow.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<int>("PublishAttempts")
                        .HasColumnType("int")
                        .HasColumnName("publish_attempts");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("published_at");

                    b.HasKey("EventId");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_pending")
                        .HasFilter("[published_at] IS NULL");

                    b.ToTable("outbox", "registry");
                });

            modelBuilder.Entity("Certiflow.SupplierRegistry.Domain.ComplianceProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<bool>("HasUnpublishedChanges")
                        .HasColumnType("bit")
                        .HasColumnName("has_unpublished_changes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("published_at");

                    b.Property<int>("PublishedVersion")
                        .HasColumnType("int")
                        .HasColumnName("published_version");

                    b.HasKey("Id");

                    b.ToTable("compliance_profiles", "registry");
                });

            modelBuilder.Entity("Certiflow.SupplierRegistry.Domain.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("TradingName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("trading_name");

                    b.HasKey("Id");

                    b.ToTable("suppliers", "registry");
                });

            modelBuilder.Entity("Certiflow.SupplierRegistry.Domain.ComplianceProfile", b =>
                {
                    b.OwnsMany("Certiflow.SupplierRegistry.Domain.Requirement", "Requirements", b1 =>
                        {
                            b1.Property<Guid>("category_id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("requirement_id");

                            b1.PrimitiveCollection<string>("AcceptedIssuers")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("accepted_issuers");

                            b1.Property<decimal>("AutoAcceptThreshold")
                                .HasPrecision(3, 2)
                                .HasColumnType("decimal(3,2)")
                                .HasColumnName("auto_accept_threshold");

                            b1.Property<bool>("IsDeprecated")
                                .HasColumnType("bit")
                                .HasColumnName("is_deprecated");

                            b1.Property<bool>("IsMandatory")
                                .HasColumnType("bit")
                                .HasColumnName("is_mandatory");

                            b1.Property<int>("MinValidityDays")
                                .HasColumnType("int")
                                .HasColumnName("min_validity_days");

                            b1.Property<int>("RenewalLeadTimeDays")
                                .HasColumnType("int")
                                .HasColumnName("renewal_lead_time_days");

                            b1.Property<bool>("RequiresIssuerMatch")
                                .HasColumnType("bit")
                                .HasColumnName("requires_issuer_match");

                            b1.HasKey("category_id", "Id");

                            b1.ToTable("requirements", "registry");

                            b1.WithOwner()
                                .HasForeignKey("category_id");

                            b1.OwnsOne("Certiflow.SupplierRegistry.Domain.DocumentType", "DocumentType", b2 =>
                                {
                                    b2.Property<Guid>("Requirementcategory_id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("RequirementId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("document_type");

                                    b2.HasKey("Requirementcategory_id", "RequirementId");

                                    b2.ToTable("requirements", "registry");

                                    b2.WithOwner()
                                        .HasForeignKey("Requirementcategory_id", "RequirementId");
                                });

                            b1.Navigation("DocumentType")
                                .IsRequired();
                        });

                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("Certiflow.SupplierRegistry.Domain.Supplier", b =>
                {
                    b.OwnsOne("Certiflow.SupplierRegistry.Domain.CountryCode", "Country", b1 =>
                        {
                            b1.Property<Guid>("SupplierId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("country_code");

                            b1.HasKey("SupplierId");

                            b1.ToTable("suppliers", "registry");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId");
                        });

                    b.OwnsOne("Certiflow.SupplierRegistry.Domain.RegistrationNumber", "RegistrationNumber", b1 =>
                        {
                            b1.Property<Guid>("SupplierId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("registration_number_normalized");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("registration_number");

                            b1.HasKey("SupplierId");

                            b1.ToTable("suppliers", "registry");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId");
                        });

                    b.OwnsMany("Certiflow.SupplierRegistry.Domain.SupplierContact", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("supplier_id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("contact_id");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("bit")
                                .HasColumnName("is_primary");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("name");

                            b1.Property<string>("Role")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("role");

                            b1.HasKey("supplier_id", "Id");

                            b1.ToTable("supplier_contacts", "registry");

                            b1.WithOwner()
                                .HasForeignKey("supplier_id");

                            b1.OwnsOne("Certiflow.SupplierRegistry.Domain.EmailAddress", "Email", b2 =>
                                {
                                    b2.Property<Guid>("SupplierContactsupplier_id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("SupplierContactId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("nvarchar(256)")
                                        .HasColumnName("email");

                                    b2.HasKey("SupplierContactsupplier_id", "SupplierContactId");

                                    b2.ToTable("supplier_contacts", "registry");

                                    b2.WithOwner()
                                        .HasForeignKey("SupplierContactsupplier_id", "SupplierContactId");
                                });

                            b1.Navigation("Email")
                                .IsRequired();
                        });

                    b.Navigation("Contacts");

                    b.Navigation("Country")
                        .IsRequired();

                    b.Navigation("RegistrationNumber")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
