// <auto-generated />
using System;
using Certiflow.Compliance.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Certiflow.Compliance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ComplianceDbContext))]
    [Migration("20260821200519_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("compliance")
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Certiflow.Compliance.Domain.SupplierComplianceState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset?>("LastEvaluatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_evaluated_at");

                    b.Property<int>("ProfileVersion")
                        .HasColumnType("int")
                        .HasColumnName("profile_version");

                    b.Property<string>("overall_status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("supplier_compliance", "compliance");
                });

            modelBuilder.Entity("Certiflow.Compliance.Infrastructure.Persistence.ProfileVersionRecord", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<int>("ProfileVersion")
                        .HasColumnType("int")
                        .HasColumnName("profile_version");

                    b.Property<string>("RequirementsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requirements_json");

                    b.HasKey("CategoryId");

                    b.ToTable("profile_versions", "compliance");
                });

            modelBuilder.Entity("Certiflow.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("received_at");

                    b.HasKey("MessageId");

                    b.ToTable("inbox", "compliance");
                });

            modelBuilder.Entity("Certiflow.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<int>("PublishAttempts")
                        .HasColumnType("int")
                        .HasColumnName("publish_attempts");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("published_at");

                    b.HasKey("EventId");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_pending")
                        .HasFilter("[published_at] IS NULL");

                    b.ToTable("outbox", "compliance");
                });

            modelBuilder.Entity("Certiflow.Compliance.Domain.SupplierComplianceState", b =>
                {
                    b.OwnsMany("Certiflow.Compliance.Domain.Obligation", "Obligations", b1 =>
                        {
                            b1.Property<Guid>("supplier_id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("requirement_id");

                            b1.Property<string>("CurrentEvidence")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("current_evidence_json");

                            b1.Property<bool>("IsApplicable")
                                .HasColumnType("bit")
                                .HasColumnName("is_applicable");

                            b1.Property<Guid?>("PendingDocumentId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("pending_document_id");

                            b1.Property<string>("Specification")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("specification_json");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("status");

                            b1.Property<string>("_history")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("history_json");

                            b1.HasKey("supplier_id", "Id");

                            b1.ToTable("obligations", "compliance");

                            b1.WithOwner()
                                .HasForeignKey("supplier_id");
                        });

                    b.Navigation("Obligations");
                });
#pragma warning restore 612, 618
        }
    }
}
