// <auto-generated />
using System;
using Certiflow.Verification.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Certiflow.Verification.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VerificationDbContext))]
    [Migration("20260821200437_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("verification")
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Certiflow.Persistence.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("received_at");

                    b.HasKey("MessageId");

                    b.ToTable("inbox", "verification");
                });

            modelBuilder.Entity("Certiflow.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<int>("PublishAttempts")
                        .HasColumnType("int")
                        .HasColumnName("publish_attempts");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("published_at");

                    b.HasKey("EventId");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_pending")
                        .HasFilter("[published_at] IS NULL");

                    b.ToTable("outbox", "verification");
                });

            modelBuilder.Entity("Certiflow.Verification.Domain.ReviewTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("review_task_id");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("assigned_to");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateOnly?>("CurrentEvidenceExpiresOn")
                        .HasColumnType("date")
                        .HasColumnName("current_evidence_expires_on");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("document_id");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("document_type");

                    b.Property<Guid>("ExtractionJobId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("extraction_job_id");

                    b.Property<decimal>("OverallConfidence")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("overall_confidence");

                    b.Property<string>("RaisedReason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("raised_reason");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("requirement_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_review_tasks_document");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_review_tasks_status");

                    b.ToTable("review_tasks", "verification");
                });

            modelBuilder.Entity("Certiflow.Verification.Infrastructure.Persistence.DocumentRecord", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("document_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("file_name");

                    b.Property<DateTimeOffset>("StoredAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("stored_at");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("DocumentId");

                    b.ToTable("documents", "verification");
                });

            modelBuilder.Entity("Certiflow.Verification.Domain.ReviewTask", b =>
                {
                    b.OwnsOne("Certiflow.Verification.Domain.Verdict", "Verdict", b1 =>
                        {
                            b1.Property<Guid>("ReviewTaskId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("DecidedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("verdict_decided_at");

                            b1.Property<string>("DecidedBy")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("verdict_decided_by");

                            b1.Property<string>("Decision")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("verdict_decision");

                            b1.Property<string>("Reason")
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)")
                                .HasColumnName("verdict_reason");

                            b1.Property<string>("ReasonNote")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("verdict_reason_note");

                            b1.HasKey("ReviewTaskId");

                            b1.ToTable("review_tasks", "verification");

                            b1.WithOwner()
                                .HasForeignKey("ReviewTaskId");
                        });

                    b.OwnsMany("Certiflow.Verification.Domain.FieldReview", "FieldReviews", b1 =>
                        {
                            b1.Property<Guid>("review_task_id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Id")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("field_name");

                            b1.Property<string>("AcceptedValue")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("accepted_value");

                            b1.Property<int?>("CitationPage")
                                .HasColumnType("int")
                                .HasColumnName("citation_page");

                            b1.Property<string>("CitationSnippet")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("citation_snippet");

                            b1.Property<decimal>("Confidence")
                                .HasPrecision(3, 2)
                                .HasColumnType("decimal(3,2)")
                                .HasColumnName("confidence");

                            b1.Property<bool>("IsMandatory")
                                .HasColumnType("bit")
                                .HasColumnName("is_mandatory");

                            b1.Property<DateTimeOffset?>("ResolvedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("resolved_at");

                            b1.Property<string>("ResolvedBy")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("resolved_by");

                            b1.Property<string>("ReviewerNote")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("reviewer_note");

                            b1.Property<string>("ScoringNote")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("scoring_note");

                            b1.Property<string>("SuggestedValue")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("suggested_value");

                            b1.Property<bool>("WasCorrected")
                                .HasColumnType("bit")
                                .HasColumnName("was_corrected");

                            b1.HasKey("review_task_id", "Id");

                            b1.ToTable("field_reviews", "verification");

                            b1.WithOwner()
                                .HasForeignKey("review_task_id");
                        });

                    b.Navigation("FieldReviews");

                    b.Navigation("Verdict");
                });
#pragma warning restore 612, 618
        }
    }
}
